repos:
  - repo: local
    hooks:
      # 開発整備時点でテストがないのでコメントアウト
      #      - id: pytest
      #        name: pytest
      #        entry: .venv/bin/pytest
      #        language: system
      #        types: [python]
      #        pass_filenames: false
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy .
        language: system
        types: [python]
        pass_filenames: false
        exclude: ^src/django_tutorial/mysite|^src/django_tutorial/manage.py
      - id: ruff-check
        name: ruff check
        entry: .venv/bin/ruff check
        language: system
        types: [python]
        exclude: ^src/django_tutorial/mysite|^src/django_tutorial/manage.py
      - id: ruff-format
        name: ruff format
        entry: .venv/bin/ruff format
        language: system
        types: [python]
        exclude: ^src/django_tutorial/mysite|^src/django_tutorial/manage.py
